In [1]:
import numpy as np 


In [23]:
#sigmoid fonkisyonu veya Lojistik Aktivasyon Fonksiyonu
# onun  sonuç aralığı [0 dan 1 kadar] veya evet hayir gibi sonuc bulmak icin bir denklemdir 
#denklemin sekili  1/(1+e^(-x))

def sigmoid (x):
    return 1.0/(1+np.exp(-x))    

In [24]:
#sigmoid`in türevi 
def sigmoid_derivative(x):
    return x * (1.0 -x )          # denklemin turevi alma

In [25]:
class NeuralNetwork:
    
    '''"self" miras alındığında orginal sınıfın değişkenleri etkelenmesin diye değişme olduğu sürece''' 
    #sınır"ın contractöru  iki parametre alsın
    def __init__ (self , x , y):
        #input bir değişkendir ve x"n değeri almakta
        self.input        = x
        print('intput \n' ,self.input )
        print ()
        
        # weights1 ve weights2 rastgele değerler alsın ve onun boyutu weights1 için x"n satırlarına  göre ve 4 sütun
        #weights 1 ve 2 Q teta gibi her "future" geleck değişkeni için bir tetası var 
        self.weights1 = np.random.rand(self.input.shape[1],4)
        print('weights1 _ tetalar 1\n',self.weights1)
        print()
        # weights2 ise 4 satir bir sütun 
        self.weights2= np.random.rand(4,1)
        print('wights2  _ tetalar 2 \n',self.weights2)
        print()
        # y matrisi gerçek sonuçlar temsil ediyor  ve onlara göre tahmin yapılacaktır
        self.y  = y 
        print('y \n',self.y)
        print()
        
        #output bir değişken dir ve y matirsin aynı boyut olsun , tahmin edilmiş sonuçlar matrisi
        self.output       =np.zeros(self.y.shape)
        print('y"i göre  olacak boş sonuç matrisi \n')
        print('output  \n',self.output)
        print()
    
    # inputlardan başlayarak output"a kadar her katmandaki Q "tetalar"  onun "future" ile çarpıp ve sigmid fonk. içinde uygula 
    #np.dot ise matris çarpma işlemi yapılır yani teta matrisi input matrisi ile çarpılıyor ve output te öyle 
    def feedforward(self):
        self.layer1= sigmoid(np.dot(self.input,self.weights1))
        #print('layer 1\n',self.layer1)
        #print()
        self.output= sigmoid(np.dot(self.layer1,self.weights2))
        #print('output  \n',self.output)
        #print()
        
    # geri gelerek tetalara (dengeleme) düzeltme yapılır yani buldumuz 
    def backprop(self):   #back propagation 
        d_weights2=np.dot(self.layer1.T ,(2*(self.y -self.output)*sigmoid_derivative(self.output)))
        #print('d_weigts2 \n',d_weights2)
        #print()
        d_weights1= np.dot(self.input.T,
                           (np.dot(2*(self.y-self.output)*sigmoid_derivative(self.output),
                                   self.weights2.T)*sigmoid_derivative(self.layer1)))
        #print('d_weights1\n',d_weights1)
        #print()
        
        #update the weights with the derivative (slope) of the loss function 
        #tetalara güncelleme yapılımaktadır ve bu işlemei eğirisini türev alarak olur 
        self.weights1 += d_weights1
        self.weights2 += d_weights2 


        
        

In [26]:
#np.array    [0 0 1] şekili çevirir vergül yok ederek
#            [0 1 1] 
#            [1 0 1] 
#            [1 1 1]
#  bu veriyi göre eğitip y sonuçlara           
x= np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

y= np.array([[0],
            [1],
            [1],
            [0]])
        
nn= NeuralNetwork(x,y)
for i in range(1000):
    nn.feedforward()
    nn.backprop()
print('---------------------')

intput 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights1 _ tetalar 1
 [[0.16732768 0.10058377 0.27262621 0.57678234]
 [0.72012303 0.73778007 0.84996007 0.49559074]
 [0.07924985 0.31359854 0.00542485 0.45778809]]

wights2  _ tetalar 2 
 [[0.1451824 ]
 [0.74208118]
 [0.69068037]
 [0.58835956]]

y 
 [[0]
 [1]
 [1]
 [0]]

y"i göre  olacak boş sonuç matrisi 

output  
 [[0.]
 [0.]
 [0.]
 [0.]]

---------------------


In [27]:
#bin kez iterasyonu yaptıkten sonra y'e çok yakın sonucu elde ettik 
print(nn.output)

[[0.01536837]
 [0.96069298]
 [0.96285911]
 [0.04712544]]


In [28]:
# 10000 kez iterasyon yaparsak  tabi ki bu matris küçük olduğu için hızlı olur ama büyük datalar olunca günler alınır
for i in range(10000):
    nn.feedforward()
    nn.backprop()
print(nn.output)

[[0.00276301]
 [0.99065435]
 [0.99089146]
 [0.01144073]]
